#!/bin/bash

if [ $(id -u) -ne 0 ]; then
  echo "Error: Must run $0 as root!"
  exit -1
fi

if [ $# -e 0 ]; then 
  echo "Usage: $0 COUNTRY-CODE [COUNTRY-CODE]..."
  echo "Example: \"$0 AQ ATA\" blocks those pesky Antarctic scientists"
  exit -2
fi

for CC in "$@"; do
  if iptables -I INPUT -m geoip --src-cc $CC -j DROP ; then
    echo "Added geoip block for country code $CC"
  fi
done
